// import Image from "next/image";

// export default function Home() {
//   return (
//     <div>
//       <w3m-button />
//     </div>
//   );
// }
"use client";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PlusIcon, ArrowUpRightIcon } from "@heroicons/react/20/solid";
import { useWeb3ModalAccount } from "@web3modal/ethers/react";
import SafeApiKit, { OwnerResponse } from "@safe-global/api-kit";

export default function Home() {
  const router = useRouter();

  const { address, chainId, isConnected } = useWeb3ModalAccount();
  const [data, setData]: any = useState([]);
  const [mounting, setMounting] = useState(false);

  const getWallets = async () => {
    try {
      const chainId: bigint = BigInt(11155111);
      const apiKit = new SafeApiKit({
        chainId,
      });
      const safes: OwnerResponse = await apiKit.getSafesByOwner(address);
      setData(safes.safes);
    } catch (err) {
      console.log(err, "getWallets");
    }
  };

  useEffect(() => {
    setMounting(true);
  }, []);

  useEffect(() => {
    if (address) {
      getWallets();
    }
  }, [address]);

  if (!mounting) {
    return null;
  }

  return (
    <>
      <Head>
        <title>SecuredWal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" rounded-xl mt-3 py-6 px-7 bg-gray-900 m-2 font-['DM_Sans'] xl:mx-20 xl:mt-6 xl:py-40  xl:px-20">
        <div className="text-5xl font-['DM_Sans']	tracking-wide xl:flex xl:gap-4">
          <p>Welcome to</p>
          <p>SecuredWal</p>
        </div>
        <div className="text-lg mt-2 text-gray-400	font-['DM_Sans']">
          <p>A New Era of Crptocurrency Smart Wallet</p>
        </div>
        <div className="xl:flex xl:gap-10">
          <div className="bg-white text-gray-800 p-7 mt-4 w-[310px] rounded-lg">
            <PlusIcon className="h-14 w-12 font-bold  text-gray-900"></PlusIcon>
            <p className="text-xl mt-2 font-bold">Create New Wallet</p>
            <p className="text-md mt-2">
              A new wallet that is controlled by one or multiple owners.
            </p>
            <button
              className="bg-blue-500 hover:bg-blue-700 text-white font px-4 py-2 font-bold tracking-wider mt-2 rounded-lg"
              onClick={() => router.push("/create")}
            >
              Create new wallet
            </button>
          </div>
          <div className="bg-white text-gray-800 p-7 mt-4 w-[310px] rounded-lg">
            <ArrowUpRightIcon className="h-14 w-12 font-bold  text-gray-900"></ArrowUpRightIcon>
            <p className="text-xl mt-2 font-bold">Use existing Wallet</p>

            <p className="text-md mt-2">
              {address
                ? "Click on use button to use that wallet"
                : "Connect wallet to fetch existing wallets"}
            </p>
            {!address ? (
              <div className="mt-2">
                <w3m-button />
              </div>
            ) : (
              <div>
                {data.length > 0 ? (
                  <div className="mt-2">
                    {data.map((item: any, index: number) => (
                      <div
                        key={index}
                        className="flex items-center justify-between gap-2 mt-2 bg-gray-900 border border-gray-600 rounded-md px-3 py-2 text-sm tracking-wide focus:outline-none"
                      >
                        <div className="">
                          <p className="text-gray-200">
                            {item.slice(0, 8)}....
                            {item.slice(-8)}
                          </p>
                        </div>
                        <button
                          className="bg-blue-500 hover:bg-blue-700 text-white font px-4 py-1 rounded"
                          onClick={() => router.push("/wallet/" + item)}
                        >
                          use
                        </button>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div>
                    <p className="text-lg mt-3">
                      No wallet found create a new wallet
                    </p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
